Got this error on a previous run:
```
  File "/usr/local/lib/python3.6/dist-packages/rl_coach/level_manager.py", line 98, in <listcomp>
    [agent.handle_episode_ended() for agent in self.agents.values()]
  AttributeError: 'CompositeAgent' object has no attribute 'handle_episode_ended'
```

Found out that `handle_episode_ended()` is not in `AgentInterface` even so I fixed that (as it's obviously a required element).

Then I added it to `CompositeAgent`.